### ISSUE TITLE
image index and mosh index are not aligned

### ISSUE THREAD

**Issue by YongtaoGe** [sha2nkt/moyo_toolkit#5]
Hi, @sha2nkt How can I get the corresponding image index from the mosh npz file? 

I use the 'img_frame = (mosh_frame // 2) + frame_offset' to get img_frame id, and set frame_offset=1.

However, I found some mosh files are not aligned well with the image.

For example, 
```
yogi_body_hands_03596_Boat_Pose_or_Paripurna_Navasana_-e_YOGI_Cam_05_0061.jpg
```

![49_train220923_yogi_body_hands_03596_Boat_Pose_or_Paripurna_Navasana_-e_YOGI_Cam_05_0061](https://github.com/sha2nkt/moyo_toolkit/assets/22744013/63ee602d-1f98-4b4e-a3e3-f08307c0a020)

By the way, I do not understand the meaning of the selected frames in this file. I wonder if you make it a bit more clear.

https://github.com/sha2nkt/moyo_toolkit/blob/3ad37fbb00fe23deca39395479a159269b107e0e/moyo/utils/constants.py

**Comment by sha2nkt** [comment]
Hi, 
If you follow the pressure evaluation script, we save the image frame [here](https://github.com/sha2nkt/moyo_toolkit/blob/3ad37fbb00fe23deca39395479a159269b107e0e/moyo/eval/pressure_map_evaluation.py#L321) and the corresponding smplx fit [here](https://github.com/sha2nkt/moyo_toolkit/blob/3ad37fbb00fe23deca39395479a159269b107e0e/moyo/eval/pressure_map_evaluation.py#L359). Is this what you are doing as well? 

Due to synchronization errors, the image frame might be off by a single frame compared to the pose parameters but it shouldn't be noticeably different. 

The `selected_frames` are just the frames where the person is actually in the Yoga pose. These were manually determined.
